/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module tt_um_josue_olivos_alu(ui_in, uo_out, uio_in, uio_out, uio_oe, ena, clk, rst_n);
  input [7:0] ui_in;
  wire [7:0] ui_in;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  input ena;
  wire ena;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire carry_out;
  wire zero_flag;
  sky130_fd_sc_hd__and3b_2 _061_ (
    .A_N(uio_in[2]),
    .B(uio_in[0]),
    .C(uio_in[1]),
    .X(_000_)
  );
  sky130_fd_sc_hd__nand2_2 _062_ (
    .A(ui_in[4]),
    .B(ui_in[0]),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor3b_2 _063_ (
    .A(uio_in[2]),
    .B(uio_in[1]),
    .C_N(uio_in[0]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__a221oi_2 _064_ (
    .A1(ui_in[4]),
    .A2(ui_in[0]),
    .B1(uio_in[2]),
    .B2(uio_in[0]),
    .C1(uio_in[1]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__o22a_2 _065_ (
    .A1(ui_in[4]),
    .A2(ui_in[0]),
    .B1(_000_),
    .B2(_003_),
    .X(_004_)
  );
  sky130_fd_sc_hd__nor3b_2 _066_ (
    .A(uio_in[2]),
    .B(uio_in[0]),
    .C_N(uio_in[1]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__and3_2 _067_ (
    .A(uio_in[2]),
    .B(uio_in[0]),
    .C(uio_in[1]),
    .X(_006_)
  );
  sky130_fd_sc_hd__a32o_2 _068_ (
    .A1(ui_in[4]),
    .A2(ui_in[0]),
    .A3(_005_),
    .B1(_006_),
    .B2(ui_in[1]),
    .X(_007_)
  );
  sky130_fd_sc_hd__nand3b_2 _069_ (
    .A_N(uio_in[1]),
    .B(uio_in[0]),
    .C(uio_in[2]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nor2_2 _070_ (
    .A(ui_in[0]),
    .B(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__or3_2 _071_ (
    .A(_004_),
    .B(_007_),
    .C(_009_),
    .X(uo_out[0])
  );
  sky130_fd_sc_hd__or2_2 _072_ (
    .A(ui_in[1]),
    .B(ui_in[5]),
    .X(_010_)
  );
  sky130_fd_sc_hd__nand2_2 _073_ (
    .A(ui_in[1]),
    .B(ui_in[5]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__xnor2_2 _074_ (
    .A(ui_in[1]),
    .B(ui_in[5]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__or3b_2 _075_ (
    .A(uio_in[0]),
    .B(uio_in[1]),
    .C_N(uio_in[2]),
    .X(_013_)
  );
  sky130_fd_sc_hd__nor2_2 _076_ (
    .A(_012_),
    .B(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a31o_2 _077_ (
    .A1(ui_in[1]),
    .A2(ui_in[5]),
    .A3(_005_),
    .B1(_014_),
    .X(_015_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _078_ (
    .A1_N(ui_in[1]),
    .A2_N(_008_),
    .B1(_006_),
    .B2(ui_in[2]),
    .X(_016_)
  );
  sky130_fd_sc_hd__and3b_2 _079_ (
    .A_N(uio_in[0]),
    .B(uio_in[1]),
    .C(uio_in[2]),
    .X(_017_)
  );
  sky130_fd_sc_hd__a22o_2 _080_ (
    .A1(_000_),
    .A2(_010_),
    .B1(_017_),
    .B2(ui_in[0]),
    .X(_018_)
  );
  sky130_fd_sc_hd__nand2b_2 _081_ (
    .A_N(ui_in[0]),
    .B(ui_in[4]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__o21ai_2 _082_ (
    .A1(_012_),
    .A2(_019_),
    .B1(_002_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__a21oi_2 _083_ (
    .A1(_012_),
    .A2(_019_),
    .B1(_020_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_2 _084_ (
    .A(_001_),
    .B(_012_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor3_2 _085_ (
    .A(uio_in[2]),
    .B(uio_in[0]),
    .C(uio_in[1]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__or2_2 _086_ (
    .A(_001_),
    .B(_012_),
    .X(_024_)
  );
  sky130_fd_sc_hd__a31o_2 _087_ (
    .A1(_022_),
    .A2(_023_),
    .A3(_024_),
    .B1(_018_),
    .X(_025_)
  );
  sky130_fd_sc_hd__or4_2 _088_ (
    .A(_015_),
    .B(_016_),
    .C(_021_),
    .D(_025_),
    .X(uo_out[1])
  );
  sky130_fd_sc_hd__or2_2 _089_ (
    .A(ui_in[2]),
    .B(ui_in[6]),
    .X(_026_)
  );
  sky130_fd_sc_hd__and2_2 _090_ (
    .A(ui_in[2]),
    .B(ui_in[6]),
    .X(_027_)
  );
  sky130_fd_sc_hd__nand2_2 _091_ (
    .A(ui_in[2]),
    .B(ui_in[6]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_2 _092_ (
    .A(_026_),
    .B(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a21o_2 _093_ (
    .A1(_011_),
    .A2(_024_),
    .B1(_029_),
    .X(_030_)
  );
  sky130_fd_sc_hd__nand3_2 _094_ (
    .A(_011_),
    .B(_024_),
    .C(_029_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a21bo_2 _095_ (
    .A1(_030_),
    .A2(_031_),
    .B1_N(_023_),
    .X(_032_)
  );
  sky130_fd_sc_hd__and2b_2 _096_ (
    .A_N(ui_in[5]),
    .B(ui_in[1]),
    .X(_033_)
  );
  sky130_fd_sc_hd__a21o_2 _097_ (
    .A1(_012_),
    .A2(_019_),
    .B1(_033_),
    .X(_034_)
  );
  sky130_fd_sc_hd__nand2_2 _098_ (
    .A(_029_),
    .B(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__or2_2 _099_ (
    .A(_029_),
    .B(_034_),
    .X(_036_)
  );
  sky130_fd_sc_hd__and3_2 _100_ (
    .A(_002_),
    .B(_035_),
    .C(_036_),
    .X(_037_)
  );
  sky130_fd_sc_hd__nand2_2 _101_ (
    .A(_000_),
    .B(_026_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a211oi_2 _102_ (
    .A1(uio_in[2]),
    .A2(_029_),
    .B1(uio_in[1]),
    .C1(uio_in[0]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _103_ (
    .A1_N(ui_in[2]),
    .A2_N(_008_),
    .B1(_017_),
    .B2(ui_in[1]),
    .X(_040_)
  );
  sky130_fd_sc_hd__a22o_2 _104_ (
    .A1(ui_in[3]),
    .A2(_006_),
    .B1(_027_),
    .B2(_005_),
    .X(_041_)
  );
  sky130_fd_sc_hd__or4b_2 _105_ (
    .A(_039_),
    .B(_040_),
    .C(_041_),
    .D_N(_038_),
    .X(_042_)
  );
  sky130_fd_sc_hd__o21a_2 _106_ (
    .A1(_037_),
    .A2(_042_),
    .B1(_032_),
    .X(uo_out[2])
  );
  sky130_fd_sc_hd__or2_2 _107_ (
    .A(ui_in[3]),
    .B(ui_in[7]),
    .X(_043_)
  );
  sky130_fd_sc_hd__nand2_2 _108_ (
    .A(ui_in[3]),
    .B(ui_in[7]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_2 _109_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a21o_2 _110_ (
    .A1(_028_),
    .A2(_030_),
    .B1(_045_),
    .X(_046_)
  );
  sky130_fd_sc_hd__nand3_2 _111_ (
    .A(_028_),
    .B(_030_),
    .C(_045_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__and2b_2 _112_ (
    .A_N(ui_in[6]),
    .B(ui_in[2]),
    .X(_048_)
  );
  sky130_fd_sc_hd__a21o_2 _113_ (
    .A1(_029_),
    .A2(_034_),
    .B1(_048_),
    .X(_049_)
  );
  sky130_fd_sc_hd__a21boi_2 _114_ (
    .A1(_045_),
    .A2(_049_),
    .B1_N(_002_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o21a_2 _115_ (
    .A1(_045_),
    .A2(_049_),
    .B1(_050_),
    .X(_051_)
  );
  sky130_fd_sc_hd__and2_2 _116_ (
    .A(ui_in[2]),
    .B(_017_),
    .X(_052_)
  );
  sky130_fd_sc_hd__and3_2 _117_ (
    .A(ui_in[3]),
    .B(ui_in[7]),
    .C(_005_),
    .X(_053_)
  );
  sky130_fd_sc_hd__a21o_2 _118_ (
    .A1(_000_),
    .A2(_043_),
    .B1(_053_),
    .X(_054_)
  );
  sky130_fd_sc_hd__o22a_2 _119_ (
    .A1(ui_in[3]),
    .A2(_008_),
    .B1(_013_),
    .B2(_045_),
    .X(_055_)
  );
  sky130_fd_sc_hd__or3b_2 _120_ (
    .A(_052_),
    .B(_054_),
    .C_N(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__a31o_2 _121_ (
    .A1(_023_),
    .A2(_046_),
    .A3(_047_),
    .B1(_056_),
    .X(_057_)
  );
  sky130_fd_sc_hd__or2_2 _122_ (
    .A(_051_),
    .B(_057_),
    .X(uo_out[3])
  );
  sky130_fd_sc_hd__or2_2 _123_ (
    .A(uo_out[0]),
    .B(uo_out[1]),
    .X(_058_)
  );
  sky130_fd_sc_hd__nor4_2 _124_ (
    .A(uo_out[2]),
    .B(_051_),
    .C(_057_),
    .D(_058_),
    .Y(zero_flag)
  );
  sky130_fd_sc_hd__nand2b_2 _125_ (
    .A_N(ui_in[7]),
    .B(ui_in[3]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand2_2 _126_ (
    .A(_044_),
    .B(_046_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a22o_2 _127_ (
    .A1(_050_),
    .A2(_059_),
    .B1(_060_),
    .B2(_023_),
    .X(carry_out)
  );
  sky130_fd_sc_hd__conb_1 _128_ (
    .LO(uio_oe[0])
  );
  sky130_fd_sc_hd__conb_1 _129_ (
    .LO(uio_oe[1])
  );
  sky130_fd_sc_hd__conb_1 _130_ (
    .LO(uio_oe[2])
  );
  sky130_fd_sc_hd__conb_1 _131_ (
    .LO(uio_oe[3])
  );
  sky130_fd_sc_hd__conb_1 _132_ (
    .LO(uio_oe[4])
  );
  sky130_fd_sc_hd__conb_1 _133_ (
    .LO(uio_oe[5])
  );
  sky130_fd_sc_hd__conb_1 _134_ (
    .LO(uio_oe[6])
  );
  sky130_fd_sc_hd__conb_1 _135_ (
    .LO(uio_oe[7])
  );
  sky130_fd_sc_hd__conb_1 _136_ (
    .LO(uio_out[0])
  );
  sky130_fd_sc_hd__conb_1 _137_ (
    .LO(uio_out[1])
  );
  sky130_fd_sc_hd__conb_1 _138_ (
    .LO(uio_out[2])
  );
  sky130_fd_sc_hd__conb_1 _139_ (
    .LO(uio_out[3])
  );
  sky130_fd_sc_hd__conb_1 _140_ (
    .LO(uio_out[4])
  );
  sky130_fd_sc_hd__conb_1 _141_ (
    .LO(uio_out[5])
  );
  sky130_fd_sc_hd__conb_1 _142_ (
    .LO(uio_out[6])
  );
  sky130_fd_sc_hd__conb_1 _143_ (
    .LO(uio_out[7])
  );
  sky130_fd_sc_hd__conb_1 _144_ (
    .LO(uo_out[6])
  );
  sky130_fd_sc_hd__conb_1 _145_ (
    .LO(uo_out[7])
  );
  sky130_fd_sc_hd__buf_2 _146_ (
    .A(carry_out),
    .X(uo_out[4])
  );
  sky130_fd_sc_hd__buf_2 _147_ (
    .A(zero_flag),
    .X(uo_out[5])
  );
endmodule
